### ISSUE TITLE
FFmpeg missing vaapi support on Linux

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/static-ffmpeg-binaries#10]
The FFmpeg build for Linux is missing vaapi support, which is used by Shaka Streamer by default for hardware encoding on Linux.

**Comment by Brainiarc7** [comment]
> There doesn't seem to be a way to build VAAPI statically, at least not without hacking up the source.

It's possible. See [this](https://github.com/BtbN/FFmpeg-Builds/blob/master/scripts.d/50-vaapi/50-libva.sh).

**Comment by joeyparrish** [comment]
Fixed in https://github.com/shaka-project/static-ffmpeg-binaries/pull/48
